.const MC_COLOUR1 = BLUE 
.const MC_COLOUR2 = YELLOW
.const BACKGROUND_COLOUR = WHITE
.const BORDER_COLOUR = WHITE

.const ANIMATION_FRAMES = 16 
.const ANIMATION_LENGTH = ANIMATION_FRAMES*2 -2
.const UNLOCK_FRAMES = 2
.const SPEED_DELAY =1
.const INTRO_DELAY = 1

.const FADE_DELAY = 2