.const MC_COLOUR1 = BLUE 
.const MC_COLOUR2 = YELLOW
.const BACKGROUND_COLOUR = BLACK
.const BORDER_COLOUR = BLACK

.const ANIMATION_FRAMES = 20 
.const ANIMATION_LENGTH = ANIMATION_FRAMES*2 -2
.const UNLOCK_FRAMES = 6
.const SPEED_DELAY = 2
.const INTRO_DELAY = 30
